#!/usr/bin/env python
import os
import logging
import argparse
import time

def main(args):
    # < put code here >
    pass

def dir_path(path):
    """
    Type check for argparse
    """
    if os.path.isdir(path):
        return path
    raise NotADirectoryError(path)

def file_path(path):
    """
    Type check of argparse
    """
    if os.path.isfile(path):
        return path
    raise FileNotFoundError(path)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='<TODO>')
    
    parser.add_argument('--verbose', '-v', dest='verbose', action='store_true')
    
    args = parser.parse_args()
    if args.verbose is True:
        logging.basicConfig(level=logging.INFO)
    start = time.time()
    logging.info('Start.')
    main(args)
    end = time.time()
    logging.info('Finished. Time: {}'.format(end-start))
